GET http://localhost:8080/api/posts

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 0,
  "content": "Last Post"
}

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 1,
  "content": "Updated Post"
}

###

GET http://localhost:8080/api/posts/1

###

DELETE http://localhost:8080/api/posts/1

